### ISSUE TITLE
Add copyrights/license information

### ISSUE THREAD

**Issue by vazhnov** [Kyrie1965/torrentReleases#1]
Could you add information about copyrights/license, please?
It would be great to see any popular open source license.

**Comment by Kyrie1965** [comment]
Исходный код без какой-либо лицензии. Используйте его так, как вам хочется.

**Comment by vazhnov** [comment]
@Kyrie1965, почитайте пожалуйста описание cc0 [в Википедии](https://ru.wikipedia.org/wiki/%D0%9B%D0%B8%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D0%B8_%D0%B8_%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B_Creative_Commons), думаю это то что вам нужно:

>Произведение, выпущенное по CC0, передано в общественное достояние в максимальной степени, разрешенной законом. Если это невозможно по любой причине, CC0 также предоставляет простую пермиссивную лицензию в качестве запасного варианта. И произведения в общественном достоянии, и простая лицензия, предоставляемая CC0, совместимы с GNU GPL.

Если это то, что надо — добавьте, пожалуйста, упоминание где-нибудь в первых строчках кода, в комментариях:

> License: CC0 1.0 Universal or newer.
