### ISSUE TITLE
Загрузка не удалась. Пропуск фильма с ID 1140565.

### ISSUE THREAD

**Issue by korobcov** [Kyrie1965/torrentReleases#12]
Добрый день! 
я тот самый человек который это использует и доволен как слон, но случилась беда, ошибка обработки фильма... 
[tr.log.txt](https://github.com/Kyrie1965/torrentReleases/files/3721603/tr.log.txt)

**Comment by Akior** [comment]
Если быть точнее:

Traceback (most recent call last):
  File "/root/digitalreleases.py", line 1825, in <module>
    exitCode = main()
  File "/root/digitalreleases.py", line 98, in main
    movies = convertRutorResults(results)
  File "/root/digitalreleases.py", line 306, in convertRutorResults
    print("Загружены данные для фильма: " + detail["nameRU"] + ".")
UnboundLocalError: local variable 'detail' referenced before assignment

Дебаг привел к тому, что парсинг фильма с КП в loadURLContent не работает:
Ошибка соединения. Все попытки соединения израсходованы.

Видимо api изменилось ?

**Comment by korobcov** [comment]
ну, у меня вторая версия

**Comment by Crazy-kun** [comment]
У кинопоиска запросы по API не проходят, возвращается 403 ошибка.

**Comment by greenpeas** [comment]
У меня пропуск фильма только в последней записи лога.

**Comment by korobcov** [comment]
запись то последняя, но оно вообще не обновляет и соответственно не 
работает

14.10.2019 13:18, Артёмов Антон пишет:

**Comment by greenpeas** [comment]
@Kyrie1965 нам надеяться на обновления?

**Comment by Kyrie1965** [comment]
Публичная версия больше не обновляется.

**Comment by greenpeas** [comment]
Ну и смысл было тогда пиариться на хабре? Чтобы потом кинуть всех? Нехорошо поступаете.

**Comment by Kyrie1965** [comment]
> Ну и смысл было тогда пиариться на хабре? Чтобы потом кинуть всех? Нехорошо поступаете.

Антон, зря ты так пишешь, т.е. гнилые слова человека, который не хочет получить ответы. Таких обычно называют обиженными, и нормальное общество их изолирует (а в нормальных компаниях увольняют сразу). Пиара не было. Проект достаточно времени получал много исправлений и улучшений. 30 коммитов и поддержка/пояснения на Хабре в комментариях.

У тебя есть исходный код, ты можешь исправить всё самостоятельно в доступе к API Кинопоиск. Не можешь? Так кто виноват? Тебе никто ничего не должен и не обязан.

Ты можешь обратиться ко мне персонально, я тебе на коммерческой основе (дорого) предоставлю исходный код полностью рабочей и расширенной версии без поддержки (получил и свободен). Модульная структура, читаемый код с пояснениями, много нововведений и исправлений.

**Comment by Kyrie1965** [comment]
Антон, не вижу обращений, тебе нужна рабочая версия или нет? Прокукарекал и в курятник, петушок?

**Comment by greenpeas** [comment]
Спасибо за разъяснение. Ничего не нужно.
